[build]
    functions="functions"

[[redirects]]
    from="/*"
    to="/.netlify/functions/api:splat"
    status=200 

[[redirects]]
    from="/item"
    to="/.netlify/functions/api:splat"
    status=200 
