[build]
    functions="functions"

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/"
    status=200 

[[redirects]]
    to="/.netlify/functions/api:splat"
    from="/item"
    status=200 
